version: "{build}"

branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2017

environment:
  BUILD_PATH: C:\build\
  GITHUB_USERNAME: WindowerBot
  GITHUB_NAME: WindowerBot
  GITHUB_EMAIL: 39810929+WindowerBot@users.noreply.github.com
  GITHUB_TOKEN:
    secure: m6mZDtWfoHMRrfVTzY2Eq6DNFV8hlvghlTCidTng0J4SBezag38tteGczs16N/EM

init:
  - git config --global core.autocrlf input

clone_depth: 2

build_script:
  - ps: .\build

test_script:
  - ps: .\test

deploy_script:
  - ps: .\deploy
